---
title: "README"
format: html
---
Explaining the Seshat Data:
This Dataset measures factors of social complexity across various dynasties in ancient Upper Egypt. It measures factors like personal communication time, settlement population, and markers of socioeconomic complexity. Published by the Sehat Project, this dataset covers roughly 80 indicators of societal development, which have here been narrowed for the purpose of understanding the progression of Egypt’s early history. The attached graphs show three measurements across each dynasty, starting from the predynastic Naqada III period circa 3,300 BCE to the end of the First Intermediate Period that followed the collapse of the Old Kingdom circa 2,2000 BCE. This data gives insight into how the collapse of the old kingdom in Upper Egypt was marked by the emergence of strong regional powers and the decline of centralized authority. From the predynastic period, the population of Upper Egypt was steadily increasing. The unification by Upper-Egyptian king Narmer, the first Pharaoh of Dynasty I, brought peace and population boom. Through the Old Kingdom, population steadily increased. As the Old Kingdom declined, however, central authority began to wane, and regional governors asserted control over the provinces, known as Nomes. The graphs of settlement population and polity territorial extent show the decline in Upper Egypt’s relationship with the Old Kingdom state. 


The juxtaposition of increasing total population and decreasing settlement population is the key indicator of declining central authority. The Pharaoh was unable to maintain large cities for priests and traders, and regional rivalries dispersed populations. Rurification in a period of overall population increase may suggest that more people moved to yeoman farms or those owned by temples as a response to a failing economy, or indeed climate change, as some historians suggest. Lastly, the graph of polity territorial extent shows how Upper Egypt slowly broke away from the Delta. This graph is the only visual to contain a measurement for the Intermediate Period. As Upper Egypt decentralized into independent states, the maximum extent of the states were commensurate with their provincial divisions, as is noted by the sharp decline in the territorial extent data. 
A second throughline visible to astute Egyptologists is the overall shift in power away from Upper Egypt and towards the Delta as the Old Kingdom progressed. The unification of Egypt came from Upper Egypt, and Egypt was ruled from the South for several hundred years before the capital was moved to Memphis in the Delta. This data thus acts as both primary evidence for a decline in centralized authority at the end of the Old Kingdom, as well as secondary supporting evidence for historians’ qualitative conclusions that the government in the North was unable to assert power over the South at the end of the Old Kingdom, directly leading to the empowering of regional Nomarchs and the eventually breakdown of the state.


Link to dataset: https://github.com/datasets/seshat
